#Alter in live
CREATE TABLE IF NOT EXISTS CURRENT_TASK_STATUS (
  TASK         VARCHAR(255)                             NOT NULL,
  SERVER       VARCHAR(255)                             NOT NULL,
  STATUS       ENUM ('UP', 'DOWN', 'MAINTENANCE', 'NA') NOT NULL,
  LAST_UPDATED DATETIME                                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (SERVER, TASK)
)
  ENGINE INNODB;

CREATE TABLE IF NOT EXISTS SUCCESS_RECORD (
  ID     INT(11)      NOT NULL AUTO_INCREMENT,
  TASK   VARCHAR(255) NOT NULL,
  SERVER VARCHAR(255) NOT NULL,
  TIME   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
)
  ENGINE INNODB;

CREATE TABLE IF NOT EXISTS FAILURE_RECORD (
  ID     INT(11)      NOT NULL AUTO_INCREMENT,
  TASK   VARCHAR(255) NOT NULL,
  SERVER VARCHAR(255) NOT NULL,
  TIME   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ERROR  TEXT,
  PRIMARY KEY (ID)
)
  ENGINE INNODB;

CREATE TABLE FAILURE_SUMMARY (
  ID         INT(11)      NOT NULL AUTO_INCREMENT,
  TASK       VARCHAR(255) NOT NULL,
  SERVER     VARCHAR(255) NOT NULL,
  START_ID   INT(11)      NOT NULL,
  END_ID     INT(11)      NOT NULL,
  DATE       DATE         NOT NULL,
  START_TIME DATETIME     NOT NULL,
  END_TIME   DATETIME     NOT NULL,
  DOWN_TIME  INT(11)      NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE INNODB;

CREATE TABLE MAINTENANCE_SUMMARY (
  ID         INT(11)                          NOT NULL AUTO_INCREMENT,
  SERVER     VARCHAR(255)                     NOT NULL,
  TASK       VARCHAR(255)                     NOT NULL,
  DATE       DATE                             NOT NULL,
  STATUS     ENUM ('COMPLETED', 'INPROGRESS') NOT NULL,
  START_TIME DATETIME                         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  END_TIME   DATETIME,
  DOWN_TIME  INT(11),
  PRIMARY KEY (ID)
)
  ENGINE INNODB;


CREATE TABLE IF NOT EXISTS DAILY_SERVICE_STATUS (
  SERVICE   VARCHAR(255)                             NOT NULL,
  DATE      DATE                                     NOT NULL,
  STATUS    ENUM ('UP', 'DISRUPTIONS', 'DOWN', 'NA') NOT NULL,
  DOWN_TIME INT(11)                                  NOT NULL,
  PRIMARY KEY (SERVICE, DATE)
)
  ENGINE INNODB;

CREATE TABLE IF NOT EXISTS DAILY_CLOUD_STATUS (
  ID       INT(11)                                  NOT NULL AUTO_INCREMENT,
  CLOUD    VARCHAR(255)                             NOT NULL,
  DATE     DATE                                     NOT NULL,
  STATUS   ENUM ('UP', 'DISRUPTIONS', 'DOWN', 'NA') NOT NULL,
  DOWNTIME INT(11)                                  NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE INNODB;